### ISSUE TITLE
Create "combined" SBOM

### ISSUE THREAD

**Issue by kzantow** [anchore/sbom-action#23]
During the build process there can and likely should be multiple SBOMs created. An extremely common example is building a Docker image containing a Webpack bundle of front-end code. In this case, the most important SBOM is probably the build-time `node` execution (e.g. determining that `left-pad` was part of the build) but a subsequent Docker SBOM will not necessarily be determined to have the same information. Using SPDX, we can account for this using references. In order to do this, we can create a "master" SBOM with references to each of the SBOMs created during the build.

There currently exists a sub-action for accomplishing this, among other things, but needs implementation:
```yaml
- uses: anchore/sbom-action/attach@version
  with:
    sbom-artifact-match: sbom-.*spdx
```

NOTE: very open to other terms for this type of SBOM.
