### ISSUE TITLE
Allow setting scope

### ISSUE THREAD

**Issue by erhan-** [anchore/sbom-action#352]
Hello everyone,

is it possible to set --scope all-layers optionally for this action? This would show the software of the base images as well if we want to do the vulnerability scan in the next step. Or am I misunderstanding something here?

Thanks for these great tools either way!

Best regards,

Erhan

**Comment by kzantow** [comment]
Apologies for the delay @erhan- -- there currently is no option for this, but sounds like a fine addition! I'll add this to the backlog.

**Comment by kzantow** [comment]
Hi, sorry for the delay getting back to this. Today it's possible to add either a configuration file or environment variables for more advanced Syft configuration. You can accomplish this using something like:

```
     -  uses: anchore/sbom-action@main
        env:
          SYFT_SCOPE: all-layers
        with:
          image: alpine:3.15
          artifact-name: image.spdx.json
```
