### ISSUE TITLE
invalid package url type: dotnet

### ISSUE THREAD

**Issue by felickz** [anchore/sbom-action#397]
Testing out capabilities on a small .NET test repo: 

[Config](https://github.com/octodemo/Automapper.Sample/actions/runs/4265160714/workflow#L66-L70)
```yml
      - uses: anchore/sbom-action@v0
        if: runner.os != 'Windows'
        with:
          path: .
          dependency-snapshot: true
```

[Logs](https://github.com/octodemo/Automapper.Sample/actions/runs/4265160714/jobs/7424164543) showing the errror:
```
  "data": {
    "message": "invalid package url: in manifest \"ProCodeGuide.Samples.Automapper/bin/Debug/netcoreapp3.1/ProCodeGuide.Samples.Automapper.deps.json\" decoding \"pkg:dotnet/AutoMapper@9.0.0\": invalid package url type: dotnet",
    "documentation_url": "https://docs.github.com/rest/reference/dependency-graph#create-a-snapshot-of-dependencies-for-a-repository"
  }
```
